{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <label>{'Text'|i18n( 'design/standard/class/datatype' )}:</label>
    <textarea class="box" rows="10" name="ContentClass_data_text5_{$class_attribute.id}">{$class_attribute.data_text5}</textarea>
</div>

<div class="block">
    <label>{'Link'|i18n( 'design/standard/class/datatype' )}:</label>
    <input class="box" type="text" name="ContentClass_data_text4_{$class_attribute.id}" value="{$class_attribute.data_text4}" />
</div>

<div class="block">
    <label>{'Link text'|i18n( 'design/standard/class/datatype' )}:</label>
    <input class="box" type="text" name="ContentClass_data_text3_{$class_attribute.id}" value="{$class_attribute.data_text3}" />
</div>
