{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{foreach ezini('RegionalSettings', 'SiteLanguageList') as $locale}
    <div class="block">
    <fieldset>
        <legend>{fetch( 'content', 'locale', hash( 'locale_code', $locale ) ).language_name|wash()}</legend>
        <div style="margin-bottom: 10px">
            <label><img style="max-width:none" src="/share/icons/flags/{$locale}.gif" /> {'Text'|i18n( 'design/standard/class/datatype' )}:</label>
            <textarea class="box" rows="3" name="ContentClass_text_{$class_attribute.id}[{$locale}]">{$class_attribute.content[$locale].text}</textarea>
        </div>

        <div style="margin-bottom: 10px">
            <label><img style="max-width:none" src="/share/icons/flags/{$locale}.gif" /> {'Link'|i18n( 'design/standard/class/datatype' )}:</label>
            <input class="box" type="text" name="ContentClass_link_{$class_attribute.id}[{$locale}]" value="{$class_attribute.content[$locale].link}" />
        </div>

        <div>
            <label><img style="max-width:none" src="/share/icons/flags/{$locale}.gif" /> {'Link text'|i18n( 'design/standard/class/datatype' )}:</label>
            <input class="box" type="text" name="ContentClass_link_text_{$class_attribute.id}[{$locale}]" value="{$class_attribute.content[$locale].link_text}" />
        </div>
    </fieldset>
    </div>
{/foreach}