{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<p>
    {$attribute.contentclass_attribute.content.text}:
    <strong>{$attribute.data_int|choose( 'No'|i18n( 'design/standard/content/datatype' ), 'Yes'|i18n( 'design/standard/content/datatype') )}</strong>
</p>
{if and(fetch(user, has_access_to, hash(module, 'gdpr', function, 'reset')), $attribute.object.can_edit, fetch(user, current_user).contentobject_id|ne($attribute.contentobject_id))}
    <p><a href="{concat('gdpr/reset/', $attribute.contentobject_id)|ezurl(no)}">{'Reset'|i18n('design/admin/user/setting')}</a></p>
{/if}