{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{$attribute.contentclass_attribute.data_text5}:
<strong>{$attribute.data_int|choose( 'No'|i18n( 'design/standard/content/datatype' ), 'Yes'|i18n( 'design/standard/content/datatype') )}</strong>